### ISSUE TITLE
Package should include a precompiled bundle

### ISSUE THREAD

**Issue by dfederm** [GeorgDangl/angular-compare-validator#2]
Currently the package only includes TypeScript so my webpack build needs to recompile this package's code.

The bad part is that it ends up using my tsconfig instead of yours, and even worse is that my tslint is running against it, and my tslint fail against your code.

Most packages produce a "dist" or "bundle" dir where the compiled output goes (published in the npm package but not pushed to git), and their package.config has a "main" field which points to the entrypoint in that dir.

Example from another project:
![image](https://user-images.githubusercontent.com/6445614/30771188-11817faa-9ff6-11e7-893f-2d3f987a6afd.png)

**Comment by GeorgDangl** [comment]
Hey David, thank you very much for finding this!

I've updated the code and created a new release, `0.1.2`, that should now both export NgModule instead of the directive itself and only include `*.d.ts` definitions and `.js` files.

**Comment by GeorgDangl** [comment]
For future me, 4fb9a0a contains an example of how the code should look like for module exports.
